print("Hello, dear friend!")
print("Welcome to the world of Python programming.")
print("Let's learn together and have fun coding!")
print("Hello, dear friend!")
print("Welcome to the world of Python programming.")
